In [1]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
array.dtype

dtype('float64')

In [3]:
tensor.dtype

torch.float64

In [4]:
#再現性の確保
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2945, 0.6369, 0.0744, 0.5050],
        [0.6904, 0.3894, 0.1524, 0.8603],
        [0.5759, 0.3549, 0.3222, 0.7752]])
tensor([[0.3879, 0.9277, 0.7132, 0.1310],
        [0.4433, 0.5532, 0.5169, 0.5806],
        [0.5154, 0.8459, 0.2595, 0.6500]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [5]:
#再現性の確保
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)#<-下の一行にしか影響しない
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [6]:
#GPU
import torch 
torch.cuda.is_available()

True

In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [8]:
torch.cuda.device_count()

1

In [9]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
#numpyはGPUに対応していない
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

In [12]:
#Exercise
SEED = 42
torch.manual_seed(SEED)
tensor = torch.rand(7, 7)
tensor2 = torch.rand(1, 7).T
multip = tensor * tensor2
multip

tensor([[1.7226e-01, 1.7865e-01, 7.4753e-02, 1.8730e-01, 7.6234e-02, 1.1732e-01,
         5.0095e-02],
        [4.0045e-03, 4.7469e-03, 6.7203e-04, 4.7158e-03, 2.9951e-03, 4.3868e-03,
         2.8646e-03],
        [2.2738e-01, 1.3175e-01, 2.7167e-01, 1.7609e-01, 8.1792e-02, 1.9251e-01,
         8.2728e-02],
        [5.1414e-02, 3.4588e-02, 9.6882e-02, 1.2268e-02, 3.1393e-02, 4.1798e-02,
         2.3224e-02],
        [4.9809e-01, 5.6077e-03, 8.6617e-01, 6.8512e-02, 8.0651e-01, 5.3088e-01,
         3.0735e-01],
        [5.2099e-01, 3.7219e-01, 5.8218e-01, 3.5721e-01, 2.2046e-01, 4.0853e-01,
         2.3469e-01],
        [5.0235e-01, 6.6921e-01, 5.5793e-01, 1.9899e-01, 5.5765e-01, 4.1681e-01,
         5.3310e-01]])